config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true, length: { minimum: 1, maximum: 123 }
	validates :description, presence: true, length: { minimum: 1, maximum: 500 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
	belongs_to :article 
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, length: { minimum: 5, maximum: 25 }
	validates_uniqueness_of :name
	has_many :article_categories
	has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	has_many :articles, dependent: :destroy
	validates :username, presence: true,
	uniqueness: { case_sensitive: false },
	length: { minimum: 2, maximum: 51 }
	VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
	uniqueness: { case_sensitive: false },
	length: { maximum: 110 },
	format: { with: VALID_EMAIL }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

  def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:alert] = "You must be logged in to perform that action!"
			redirect_to login_path
		end
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:show, :index]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def show
		# byebug
		
	end

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit
		
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:notice] = "Article saved."
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:notice] = "Article updated"
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description, :category_ids)
	end

	def require_same_user
		if current_user != @article.user && !current_user.admin?
			flash[:alert] = "You can only edit or delete your own article."
			redirect_to @article
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, except: [:index, :show]
	
	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = "Category successfully created"
			redirect_to @category
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			flash[:notice] = "Category name changed."
			redirect_to @category
		else
			render 'edit'
		end
	end

	def index
		@categories = Category.paginate(page: params[:page], per_page: 3)
	end

	def show
		@category = Category.find(params[:id])
		@articles = @category.articles.paginate(page: params[:page], per_page: 2)
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !(logged_in? && current_user.admin?)
			flash[:alert] = "Only admin can perform this action"
			redirect_to categories_path
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def home
		redirect_to articles_path if logged_in?
	end
	
	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:notice] = "Logged in successfully"
			redirect_to user
		else
			flash.now[:alert] = "Wrong email or password."
			render 'new'
		end

	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You are logged out."
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user , only: [:show, :edit, :update, :destroy]
	before_action :require_user, only: [:edit, :update]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def show
		@articles = @user.articles.paginate(page: params[:page], per_page: 2)
	end

	def index
		@users = User.paginate(page: params[:page], per_page: 2)
	end
	
	def new
		@user = User.new
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:notice] = "Your account updated successfully"
			redirect_to user_path
		else
			render 'edit'
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "Welcome to the AlphaBlog #{@user.username}!"
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def destroy
		@user.destroy
		session[:user_id] = nil if @user == current_user
		flash[:notice] = "User account and all associated content sucessfullly deleted. Sorry to see you go :("
		redirect_to root_path
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user && !current_user.admin?
			flash[:alert] = "You can only edit your own profile!"
			redirect_to user_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, options = { size: 80 })
		email_address = user.email.downcase
		hash = Digest::MD5.hexdigest(email_address)
		size = options[:size]
		gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
	end

end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8">
      <div class="card text-center mt-4 shadow nb5 bg-white rounded">
        <div class="card-header">
        created by <%= link_to article.user.username, article.user %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success"%></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
              <% if article.categories.any? %>
                <div class="mt-2 mb-2">
                  <%= render article.categories %>
                </div>
              <% end %>
          <%= link_to 'Display', article_path(article), class: "btn btn-outline-success"%>
          <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-secondary"%>
            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Ary you sure?" }, class: "btn btn-outline-danger"%>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago, modified <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<%end%></div>

app/views/articles/_form.html.erb
<div class="row justify-content-center">
	<div class="col-10">
		<%= render 'shared/errors', obj: @article %>
<%= form_with(model: @article, local: true, class: "shadow p-3 mb-3 bg-info rounded") do |f| %>
<div class="form-group row">
	<%= f.label :title, class: "col-2 col-form-label text-light" %>
	<div class="col-10">
		<%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Article title" %>
	</div>
</div>

<div class="form-group row">
	<%= f.label :description, class: "col-2 col-form-label text-light" %>
	<div class="col-10">
		<%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Article content" %>
	</div>
</div>

<div class="form-group row">
	<%= f.label :category, class: "col-2 col-form-label text-light" %>
	<div class="col-10">
		<%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Select a category" }, { class: "shadow rounded custom-select" }) %>
	</div>
</div>

<div class="form-group row justify-content-center">
	<%= f.submit class: "btn btn-outline-light btn-lg" %>
</div>

</div>

<% end %>
</div>
<div class="row justify-content-center">
	<%= link_to '[ Cancel and return to Index ]', articles_path, class: "text-info" %>
</div>

app/views/articles/edit.html.erb
<div class="container">
	<h1 class="text-center">Edit article</h1>
	<%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
<h1 class="text-center">AlphaBlog Articles</h1>

<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

</div>

app/views/articles/new.html.erb
<div class="container">
	<h1 class="text-center">Create new article</h1>
	<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
<h2 class="text-center text-success"><%= @article.title %></h2>

<div class="row justify-content-md-center">
	<div class="col-8">
<div class="card text-center mt-4 shadow nb5 bg-white rounded">
  <div class="card-header">
    created by <%= @article.user.username %>
    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
    <% if @article.categories.any? %>
      <div class="mt-2">
        <%= render @article.categories %>
      </div>
    <% end %>
  </div>
  <div class="card-body">
    <div class="card-text text-left"><%= simple_format(@article.description) %></div>
    <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
 	<%= link_to 'Edit', edit_article_path, class: "btn btn-outline-secondary"%>
	<%= link_to 'Delete', article_path, method: :delete, data: { confirm: "Ary you sure?" }, class: "btn btn-outline-danger"%>
  <% end %>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(@article.created_at) %> ago, modified <%= time_ago_in_words(@article.updated_at) %> ago</small>
  </div>
</div>
</div>
</div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-warning" %>

app/views/categories/_form.html.erb
<div class="row justify-content-center">
	<div class="col-10">
		<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, local: true, class: "shadow p-3 mb-3 bg-info rounded") do |f| %>
<div class="form-group row">
	<%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
	<div class="col-10">
		<%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter category name" %>
	</div>
</div>

<div class="form-group row justify-content-center">
	<%= f.submit class: "btn btn-outline-light btn-lg" %>
</div>

</div>

<% end %>
</div>
<div class="row justify-content-center">
	<%= link_to '[ Cancel and return to Categories ]', categories_path, class: "text-info" %>
</div>

app/views/categories/edit.html.erb
<div class="container">
	<h1 class="text-center">Edit category name</h1>
	<%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container">
<h1 class="text-center">AlphaBlog Categories list</h1>

<% @categories.each do |category| %>
  <div class="row justify-content-md-center">
    <div class="col-4">
      <div class="card text-center mt-4 shadow nb5 bg-white rounded">
        <div class="card-body">
          <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success"%></h5>
          <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
         </div>
      </div>
    </div>
  </div>
<%end%></div>

<div class="apple_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

</div>

app/views/categories/new.html.erb
<div class="container">
	<h1 class="text-center">Create your profile</h1>
	<%= render 'form' %>
</div>

app/views/categories/show.html.erb
<div class="container">
	<h1 class="text-center">Category: <%= @category.name %></h1>

		<% if logged_in? && current_user.admin? %>
	<div class="text-center mt-4"><%= link_to 'Edit category name', edit_category_path(@category), class: "btn btn-outline-secondary"%></div>
	<% end %>

	<h3 class="text-center">Articles</h3>

	<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
	</div>

	<%= render 'articles/article' %>

	<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container text-center">
    <span class="text-white">&copy; 2020, <%= link_to "AlphaBlog", root_path, class: "text-white" %></span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
	<% flash.each do |name, msg| %>
		<% if name == "notice" %>
			<div class="alert alert-success alert-dismissible fade show" role="alert">
		<% else %>
			<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<% end %>
			<%= msg %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	<% end %>
</div>
 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'AlphaBlog', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Articles</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'New article', new_article_path, class: "dropdown-item alert-success" %>
            <%= link_to "Articles", articles_path, class: "dropdown-item" %>
            <%= link_to "Categories", categories_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= "#{current_user.username}" %></a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "User profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Update your profile', edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Logout', logout_path, class: "dropdown-item", method: :delete %>
            <%= link_to 'Delete your profile', user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure? This action is irreversible!" } %>
          </div>
        </li>
       <% else %>
        <li class="nav-item">
          <%= link_to 'Signup', signup_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li> 
      <% end %>
      <% if logged_in? && current_user.admin? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin options</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Create new category', new_category_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <%= render 'layouts/navigation' %>
   <%= render 'layouts/messages' %>

   <%= yield %>
   <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

app/views/pages/home.html.erb
<div class="container" id="home-container">

<div class="jumbotron text-center text-white">
  <h1 class="display-4">This is the AlphaBlog</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <%= link_to 'Sign up', signup_path, class: "btn btn-primary btn-lg btn-success" %>
</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
	<h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
	<ul>
	<% obj.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="row justify-content-center">
	<div class="col-10">
		<%= render 'shared/errors', obj: @user %>
<%= form_with(model: @user, local: true, class: "shadow p-3 mb-3 bg-info rounded") do |f| %>
<div class="form-group row">
	<%= f.label :username, class: "col-2 col-form-label text-light" %>
	<div class="col-10">
		<%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter desired user name" %>
	</div>
</div>

<div class="form-group row">
	<%= f.label :email, class: "col-2 col-form-label text-light" %>
	<div class="col-10">
		<%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email" %>
	</div>
</div>

<div class="form-group row">
	<%= f.label :password, class: "col-2 col-form-label text-light" %>
	<div class="col-10">
		<%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose secure password" %>
	</div>
</div>

<div class="form-group row justify-content-center">
	<%= f.submit(@user.new_record? ? "Sign Up" : "Update your account", class: "btn btn-outline-light btn-lg") %>
</div>

</div>

<% end %>
</div>
<div class="row justify-content-center">
	<%= link_to '[ Cancel and return to Index ]', articles_path, class: "text-info" %>
</div>

app/views/users/edit.html.erb
<div class="container">
	<h1 class="text-center">Edit your profile</h1>
	<%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
	<h1 class="text-center mt-4">Members of AlphaBlog</h1>

<div class="apple_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<% @users.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="col-8">
      <div class="card text-center mt-4 shadow nb5 bg-white rounded">
        <div class="card-header">
        <%= link_to user.username, user %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user%></h5>
          <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
          <%= link_to 'User profile', user, class: "btn btn-outline-success"%>
          <% if logged_in? %>
            <% if user == current_user %>
              <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-secondary"%>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to 'Delete user', user_path(user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure you want to delete user and all associated articles?\nThis is irreversible operation!" } %>
            <% end %>

          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<%end%>
</div>
<div class="apple_pagination">
    <%= will_paginate @users, :container => false %>
</div>

	
</div>

app/views/users/new.html.erb
<div class="container">
	<h1 class="text-center">Create your profile</h1>
	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
	<h1 class="text-center"><%= @user.username %>'s profile</h1>
	<%= gravatar_for @user, size: 200 %>
	<% if logged_in? && @user == current_user %>
	<div class="text-center mt-4"><%= link_to 'Update your profile', edit_user_path(@user), class: "btn btn-outline-secondary"%></div>
	<% end %>

	<h3 class="text-center">Articles</h3>

	<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
	</div>

	<%= render 'articles/article' %>

	<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
	</div>